import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { client } from "src/libs/client";
import type { Blogs } from "src/types/types";

type Props = {
  blogs: Blogs;
}

export const getStaticProps: GetStaticProps = async () => {
  const data: Blogs = await client.get({ endpoint: "blog" });

  return {
    props: {
      blogs: data,
    },
  };
};

const Blog: NextPage<Props> = (props) => {
  return (
    <div>
      <Head>
        <title>Gabutech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ul>
          {props.blogs.contents.map((blog) => {
            return (
              <li key={blog.id}>
                <Link href={`/blog/${blog.id}`}>
                  <a>{blog.title}</a>
                </Link>
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
};

export default Blog;
